# Change these first
owner: otelseasy # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: otelseasy
    url: https://otelseasy.com/
    icon: https://static.otelseasy.com/skin/images/agent_login/logo.png
  - name: stage-otelseasy
    url: https://stage.otelseasy.com/
    icon: https://static.otelseasy.com/skin/images/agent_login/logo.png
  - name: api
    url: $AVAIL_SITE
    method: POST
    expectedStatusCodes:
      - 200
      - 201
      - 401


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  theme: night
  cname: status.otelseasy.com # Custom CNAME
  # baseUrl: /status
  name: oe
  logoUrl: https://static.otelseasy.com/skin/images/agent_login/logo.png
  introTitle: "**Otelseasy**"
  navbar:
    - title: Status
      href: /
    - title: Otelseasy
      href: https://otelseasy.com/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
