# Change these first
owner: otelseasy # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: otelseasy
    url: https://otelseasy.com/
    icon: https://static.otelseasy.com/skin/images/agent_login/logo.png
  - name: stage-otelseasy
    url: https://stage.otelseasy.com/
    icon: https://static.otelseasy.com/skin/images/agent_login/logo.png


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  theme: night
  baseUrl: /status
  logoUrl: https://static.otelseasy.com/skin/images/agent_login/logo.png
  introTitle: "**Otelseasy** Top International Hotels and Corporate Partner Are Now Connected with otelseasy.com"
  introMessage: The Otelseasy Status Page provides real-time updates on the availability and performance of our hotel booking platform and associated services. Here, you can monitor the operational status of key systems, receive alerts about any incidents or downtime, and view information on scheduled maintenance. This page ensures transparency by offering timely updates and maintaining a historical log of system health, keeping you informed and minimizing service disruption impacts.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
    - title: Otelseasy
      href: https://otelseasy.com/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
